/**
 * Database operations module with Zod schema validation
 * 
 * Features:
 * - Runtime type validation using Zod schemas
 * - Type-safe database operations 
 * - Comprehensive exam submission workflow
 * - Automatic data transformation and validation
 * 
 * TODO: 
 * - Add error handling and logging
 * - Remove console logs in production
 * - Make all mongoose models global so they are not created every time
 * 
 * IMPORTANT!! NOTE:- when using this file, make sure to call connectToDb() first 
 * to ensure the database connection is established else it may throw an error in production
 */

import { connect, disconnect } from "./connect.js";
import { 
  getQuestionModel, 
  getExamModel, 
  getUserModel, 
  getExamSubmissionModel,
  getPromptModel,
  getExamQuestionModel
} from "./mongooseSchemas.js";
import { Types } from "mongoose"; // Import Types for ObjectId conversion
import type { Model } from "mongoose";
import type { 
  Question, 
  Exam, 
  User, 
  ExamSubmissionDocument, 
  ExamSubmission, 
  ClientQuestion, 
  TransformedExam,
  SubmitExamRequest,
  SubmitExamResponse,
  GetUserExamsResponse
} from "./schemas";   // <- generated by zod-to-mongoose

// Import new schema types
import type { Prompt } from "./schemas/promptSchemaZod.js";
import type { ExamQuestion } from "./schemas/examQuestionSchemaZod.js";

// Import validation schemas
import {
  submitExamRequestZodSchema,
  clientQuestionZodSchema,
  examSubmissionZodSchema
} from "./schemas";
import { promptZodSchema } from "./schemas/promptSchemaZod.js";
import { examQuestionZodSchema } from "./schemas/examQuestionSchemaZod.js";

// Import utility classes (these would need to be created in TypeScript)
// import LLMEvaluator from "../utils/llmEvaluator.js";
// import EmailService from "../utils/emailService.js";

const QuestionModel: Model<Question> = getQuestionModel();
const ExamModel: Model<Exam> = getExamModel();
const UserModel: Model<User> = getUserModel();
const ExamSubmissionModel: Model<ExamSubmissionDocument> = getExamSubmissionModel();
const PromptModel: Model<Prompt> = getPromptModel();
const ExamQuestionModel: Model<ExamQuestion> = getExamQuestionModel();

// All interfaces are now defined as Zod schemas in ./schemas/examSubmissionZod.ts
// This provides better type safety and runtime validation

// ExamSubmission schema and model are now handled by mongooseSchemas.ts
// using Zod schema conversion with proper indexing

// Transformation utility removed - using Zod types directly for better performance and cleaner code

/**
 * Creates an exam together with its questions.
 * All parameters must already be validated by the caller.
 */
export async function createExam(
  examTitle: string,
  examDescription: string,
  examType: string,
  examMaxMarks: number,
  passingPercentage: number,
  examDegree: string,
  examUsers: string[], // Array of user emails
  clientQuestions: ClientQuestion[]
) {
  // Validate client questions using Zod schema before inserting
  const questionsValidation = clientQuestions.map((question, index) => {
    const result = clientQuestionZodSchema.safeParse(question);
    if (!result.success) {
      throw new Error(`Question ${index + 1} validation failed: ${result.error.message}`);
    }
    return result.data;
  });

  await connect(); // throws if connection fails

  const inserted = await QuestionModel.insertMany(questionsValidation);
  const questionsForExam = inserted.map((doc, i) => ({
    questionId: doc._id.toString(),
    marks: clientQuestions[i].marks
  }));

  /* ----------------------- EXAM ------------------------- */
  const exam = new ExamModel({
    examTitle,
    examDescription,
    examType,
    examMaxMarks,
    passingPercentage,
    examDegree,
    questions: questionsForExam // <-- property name per examZodSchema
  });

  const savedExam = await exam.save();

  // Update the users with the new exam
  await UserModel.updateMany(
    { email: { $in: examUsers } }, // Find users by email
    { $push: { currentAllocatedExams: savedExam._id } } // Push the exam ID to their currentAllocatedExams array
  );

  // keep global connection open; server manages lifecycle
  return savedExam;
}
// Internal helper that returns full exam details for a user by kind
export async function getUserExams(email: string, kind: 'allocated' | 'submitted'): Promise<GetUserExamsResponse> {
  try {
    await connect();
    
    // Pull both fields to avoid a second query when switching kinds
    const user = await UserModel.findOne(
      { email }, 
      { currentAllocatedExams: 1, submittedExams: 1, _id: 0 }
    ).lean();
    
    if (!user) {
      return { error: 'No user found with that email' };
    }
    
    const rawIds = kind === 'allocated'
      ? (user.currentAllocatedExams || [])
      : (user.submittedExams || []);
    
    const examIds = rawIds.map((id: any) => id?.toString?.() ?? String(id));
    
    if (examIds.length === 0) {
      return { exams: [] };
    }
    
    // Convert string IDs to ObjectIds and fetch full exam docs
    const objectIds = examIds.map(id => Types.ObjectId.createFromHexString(id));
    const exams = await ExamModel.find({ _id: { $in: objectIds } }, { __v: 0 });
    
    const transformedExams: TransformedExam[] = exams.map(exam => ({
      id: exam._id.toString(),
      _id: exam._id.toString(),
      title: exam.examTitle,
      description: exam.examDescription,
      questions: exam.questions?.length || 0,
      duration: 60, // default placeholder
      status: 'active', // default placeholder
      createdAt: new Date().toISOString(), // placeholder
      submissions: 0 // placeholder
    }));
    
    return { exams: transformedExams };
  } catch (err) {
    console.log('Error in getUserExams:', err);
    return { error: 'Failed to retrieve exams for user' };
  }
}

export async function getQuestions(examSetId: string) {
  await connect();
  try {
    // Convert examSetId string to ObjectId
    const examSetObjectId = Types.ObjectId.createFromHexString(examSetId);
    console.log("Exam Set ObjectId:", examSetObjectId);

    const ExamId = await ExamModel.find({ _id: examSetObjectId }, { _id: 0, __v: 0 });
    console.log(ExamId);

    if (!ExamId || ExamId.length === 0) {
      console.log("No exam found with the provided ID");
      return [];
    }

    const questionIds = ExamId[0].questions.map((q: any) => {
      if (q.questionId instanceof Types.ObjectId) {
        return q.questionId;
      } else {
        return Types.ObjectId.createFromHexString(q.questionId);
      }
    });

    const results = await QuestionModel.find(
      { _id: { $in: questionIds } },
      { _id: 1, text: 1, answer: 1, options: 1, type: 1 }
    ).lean();

    const marksMap: Record<string, number> = {};
    ExamId[0].questions.forEach((q: any) => {
      marksMap[q.questionId.toString()] = q.marks;
    });

    // Create new array with marks instead of mutating
    const questionsWithMarks = results.map((question: any) => {
      const idStr = question._id.toString();
      return {
        _id: idStr, // Keep the ID as string for frontend
        text: question.text,
        answer: question.answer || 'NOT PRESENT',
        options: question.options || [],
        type: question.type,
        marks: marksMap[idStr] || 1, // Default to 1 mark if not found
      };
    });

    console.log("Fetched Questions with marks:", questionsWithMarks);
    return questionsWithMarks;
  } catch (error) {
    console.error("Error fetching questions:", error);
    return [];
  }
}

export async function getExamSetData(examSetId: string) {
  await connect();
  try {
    // Convert examSetId string to ObjectId
    const examSetObjectId = Types.ObjectId.createFromHexString(examSetId);
    console.log("Exam Set ObjectId:", examSetObjectId);

    const examSetData = await ExamModel.findOne({ _id: examSetObjectId }, { __v: 0 }).lean();

    if (!examSetData) {
      console.log("No exam set found with the provided ID");
      return null;
    }

    // Convert question IDs to strings
    examSetData.questions = examSetData.questions.map((q: any) => ({
      ...q,
      questionId: q.questionId instanceof Types.ObjectId
        ? q.questionId.toString()
        : Types.ObjectId.createFromHexString(q.questionId).toString()
    }));

    console.log("Fetched Exam Set Data:", examSetData);
    return examSetData;
  } catch (error) {
    console.error("Error fetching exam set data:", error);
    return null;
  }
}

export async function getUserIdByEmail(email: string): Promise<string | null> {
  await connect();
  try {
    const results = await UserModel.find({ useremail: email });
    if (results.length > 0) {
      return results[0]._id.toString();
    }
    return null;
  } catch (error) {
    console.log(error);
    return null;
  }
}
/**
 * Submit exam answers and trigger evaluation
 */
export async function submitExam(
  examId: string,
  studentEmail: string,
  answers: Record<string, string>,
  timeSpent: number,
  autoSubmitted: boolean = false
): Promise<SubmitExamResponse> {
  // Validate input using Zod schema
  const validationResult = submitExamRequestZodSchema.safeParse({
    examId,
    studentEmail,
    answers,
    timeSpent,
    autoSubmitted
  });
  
  if (!validationResult.success) {
    return { 
      success: false, 
      error: `Validation failed: ${validationResult.error.message}` 
    };
  }
  try {
    await connect();

    // Check if submission already exists
    const existingSubmission = await ExamSubmissionModel.findOne({
      examId,
      studentEmail
    });

    if (existingSubmission) {
      await disconnect();
      return { success: false, error: 'Exam already submitted' };
    }

    // Get student name from user model and exam title
    const [user, examDoc] = await Promise.all([
      UserModel.findOne({ email: studentEmail }),
      ExamModel.findById(examId).select({ examTitle: 1 })
    ]);

    const studentName = studentEmail.split('@')[0]; // Fallback to email prefix
    const examTitle = examDoc?.examTitle || 'Exam';

    // Create submission record
    const submission = new ExamSubmissionModel({
      examId,
      examTitle,
      studentEmail,
      studentName,
      answers,
      timeSpent,
      autoSubmitted,
      submittedAt: new Date()
    });

    const savedSubmission = await submission.save();
    console.log('Exam submission saved:', savedSubmission._id);

    // Trigger async evaluation and email (evaluation function handles its own connect/disconnect)
    evaluateAndEmailResults(savedSubmission._id.toString(), examId, answers)
      .catch(error => console.error('Error in async evaluation:', error));

    // Do not disconnect here to prevent racing with evaluation; callers manage connection lifecycle per request
    return { success: true, submissionId: savedSubmission._id.toString() };
  } catch (error) {
    console.error('Error submitting exam:', error);
    // Keep connection state unchanged here; caller/evaluator manages disconnects
    return { success: false, error: 'Failed to submit exam' };
  }
}

/**
 * Evaluate exam submission using LLM and send email
 */
async function evaluateAndEmailResults(
  submissionId: string,
  examId: string,
  answers: Record<string, string>
): Promise<void> {
  try {
    await connect();

    // Get submission
    const submission = await ExamSubmissionModel.findById(submissionId);
    if (!submission) {
      console.error('Submission not found:', submissionId);
      return;
    }

    // Get exam and questions
    const questions = await getQuestions(examId);
    if (!questions || questions.length === 0) {
      console.error('No questions found for exam:', examId);
      return;
    }

    // Get exam details
    const exam = await ExamModel.findById(examId);
    const examTitle = exam?.examTitle || 'Exam';

    console.log('Starting LLM evaluation for submission:', submissionId);

    // TODO: Implement LLM evaluation when LLMEvaluator class is available
    // const llmEvaluator = new LLMEvaluator();
    // const evaluationResult = await llmEvaluator.evaluateExam(questions, answers);

    // Mock evaluation result for now
    const evaluationResult = {
      totalMarks: 100,
      obtainedMarks: 75,
      percentage: 75,
      grade: 'B',
      overallFeedback: 'Good performance overall',
      questionEvaluations: []
    };

    // Update submission with results
    submission.evaluated = true;
    submission.evaluatedAt = new Date();
    submission.totalMarks = evaluationResult.totalMarks;
    submission.obtainedMarks = evaluationResult.obtainedMarks;
    submission.percentage = evaluationResult.percentage;
    submission.grade = evaluationResult.grade;
    submission.overallFeedback = evaluationResult.overallFeedback;

    // Update questionEvaluations using Mongoose methods
    submission.questionEvaluations.splice(0); // Clear existing
    evaluationResult.questionEvaluations.forEach((qe: any) => {
      submission.questionEvaluations.push({
        questionId: qe.questionId,
        questionText: qe.questionText,
        answer: qe.answer,
        marks: qe.marks,
        allocatedMarks: qe.allocatedMarks,
        feedback: qe.feedback,
        suggestions: qe.suggestions
      });
    });

    await submission.save();
    console.log('Evaluation results saved for submission:', submissionId);

    // TODO: Send email when EmailService is available
    // const emailService = new EmailService();
    // const emailSent = await emailService.sendExamResults(
    //   submission.studentEmail,
    //   submission.studentName || submission.studentEmail,
    //   examTitle,
    //   evaluationResult
    // );

    const emailSent = false; // Mock for now

    if (emailSent) {
      submission.emailSent = true;
      submission.emailSentAt = new Date();
      await submission.save();
      console.log('Email sent successfully for submission:', submissionId);
    } else {
      console.error('Failed to send email for submission:', submissionId);
    }

    await disconnect();
  } catch (error) {
    console.error('Error in evaluation and email process:', error);
    // Attempt a safe disconnect; ignore errors
    try {
      await disconnect();
    } catch { }
  }
}

/**
 * Get exam submission results
 */
export async function getExamSubmission(examId: string, studentEmail: string): Promise<ExamSubmission | null> {
  try {
    await connect();

    const submission: ExamSubmission | null = await ExamSubmissionModel.findOne({
      examId,
      studentEmail
    }).lean();

    // keep global connection open; server manages lifecycle
    if (!submission) return null;

    // Fallback: populate examTitle for legacy records
    if (!submission.examTitle) {
      try {
        const exam = await ExamModel.findById(examId).select({ examTitle: 1 });
        submission.examTitle = exam?.examTitle;
      } catch { }
    }

    return submission; // No transformation needed - Zod types match database structure
  } catch (error) {
    console.error('Error getting exam submission:', error);
    return null;
  }
}

/**
 * Get all submissions for an exam (for admin/instructor)
 */
export async function getAllExamSubmissions(examId: string): Promise<ExamSubmission[]> {
  try {
    await connect();

    const submissions: ExamSubmission[] = await ExamSubmissionModel.find({ examId }).lean();

    // keep global connection open; server manages lifecycle
    return submissions; // No transformation needed - Zod types match database structure
  } catch (error) {
    console.error('Error getting exam submissions:', error);
    // keep global connection open; server manages lifecycle
    return [];
  }
}

/**
 * Get all submissions for an exam (for admin/instructor)
 */
export async function getUsersExamSubmissions(examId: string): Promise<ExamSubmission[]> {
  try {
    await connect();

    // Use the correct model (ExamSubmissionModel)
    const submissions: ExamSubmission[] = await ExamSubmissionModel.find({ examId }).lean();

    // keep global connection open; server manages lifecycle
    return submissions; // No transformation needed - Zod types match database structure
  } catch (error) {
    console.error('Error getting exam submissions:', error);
    // keep global connection open; server manages lifecycle
    return [];
  }
}

/**
 * Get a user's submission history across all exams
 */
export async function getUserSubmissionHistory(studentEmail: string): Promise<ExamSubmission[]> {
  try {
    await connect();

    const submissions: ExamSubmission[] = await ExamSubmissionModel.find({ studentEmail }).lean();

    return submissions; // No transformation needed - Zod types match database structure
  } catch (error) {
    console.error('Error getting user submission history:', error);
    return [];
  }
}

// ============================================================================
// NEW SCHEMA OPERATIONS - Prompt (Central Question Library)
// ============================================================================

/**
 * Create a new prompt in the central question library
 * Used by: OCR pipeline, LLM generator, manual question creation
 */
export async function createPrompt(promptData: {
  questionText: string;
  subject: string;
  topic?: string;
  generateVia: 'llm' | 'ocr' | 'user';
  source?: string;
  ocrConfidence?: number;
  createdBy: string;
  bloomsLevel?: 'remember' | 'understand' | 'apply' | 'analyze' | 'evaluate' | 'create';
}): Promise<{ success: boolean; promptId?: string; error?: string }> {
  try {
    // Validate input using Zod schema
    const validationResult = promptZodSchema.safeParse({
      ...promptData,
      _id: undefined, // Let MongoDB generate the ID
      createdAt: new Date()
    });

    if (!validationResult.success) {
      return { 
        success: false, 
        error: `Validation failed: ${validationResult.error.message}` 
      };
    }

    await connect();

    const prompt = new PromptModel(validationResult.data);
    const savedPrompt = await prompt.save();

    console.log('Prompt created:', savedPrompt._id);
    return { success: true, promptId: savedPrompt._id.toString() };
  } catch (error) {
    console.error('Error creating prompt:', error);
    return { success: false, error: 'Failed to create prompt' };
  }
}

/**
 * Bulk create prompts (used by OCR batch processing)
 */
export async function createPromptsBulk(promptsData: Array<{
  questionText: string;
  subject: string;
  topic?: string;
  generateVia: 'llm' | 'ocr' | 'user';
  source?: string;
  ocrConfidence?: number;
  createdBy: string;
  bloomsLevel?: 'remember' | 'understand' | 'apply' | 'analyze' | 'evaluate' | 'create';
}>): Promise<{ success: boolean; promptIds?: string[]; error?: string }> {
  try {
    await connect();

    // Validate all prompts
    const validatedPrompts = promptsData.map(data => {
      const result = promptZodSchema.safeParse({
        ...data,
        _id: undefined,
        createdAt: new Date()
      });
      if (!result.success) {
        throw new Error(`Prompt validation failed: ${result.error.message}`);
      }
      return result.data;
    });

    const insertedPrompts = await PromptModel.insertMany(validatedPrompts);
    const promptIds = insertedPrompts.map(p => p._id.toString());

    console.log(`Created ${promptIds.length} prompts in bulk`);
    return { success: true, promptIds };
  } catch (error) {
    console.error('Error creating prompts in bulk:', error);
    return { success: false, error: 'Failed to create prompts in bulk' };
  }
}

/**
 * Get a prompt by ID
 */
export async function getPromptById(promptId: string): Promise<Prompt | null> {
  try {
    await connect();
    const promptObjectId = Types.ObjectId.createFromHexString(promptId);
    const prompt = await PromptModel.findById(promptObjectId).lean();
    return prompt;
  } catch (error) {
    console.error('Error getting prompt:', error);
    return null;
  }
}

/**
 * Search prompts by subject and optional filters
 * Used by: Exam creation UI, question bank browser
 */
export async function searchPrompts(filters: {
  subject: string;
  topic?: string;
  bloomsLevel?: string | string[];
  generateVia?: 'llm' | 'ocr' | 'user';
  minOcrConfidence?: number;
  limit?: number;
  skip?: number;
}): Promise<Prompt[]> {
  try {
    await connect();

    const query: any = { subject: filters.subject };

    if (filters.topic) {
      query.topic = filters.topic;
    }

    if (filters.bloomsLevel) {
      query.bloomsLevel = Array.isArray(filters.bloomsLevel)
        ? { $in: filters.bloomsLevel }
        : filters.bloomsLevel;
    }

    if (filters.generateVia) {
      query.generateVia = filters.generateVia;
    }

    if (filters.minOcrConfidence !== undefined) {
      query.ocrConfidence = { $gte: filters.minOcrConfidence };
    }

    const prompts = await PromptModel.find(query)
      .sort({ createdAt: -1 })
      .limit(filters.limit || 50)
      .skip(filters.skip || 0)
      .lean();

    return prompts;
  } catch (error) {
    console.error('Error searching prompts:', error);
    return [];
  }
}

/**
 * Get low confidence OCR questions for review
 * Used by: Quality control dashboard for teachers
 */
export async function getLowConfidenceOcrPrompts(
  threshold: number = 0.85,
  limit: number = 20
): Promise<Prompt[]> {
  try {
    await connect();

    const prompts = await PromptModel.find({
      generateVia: 'ocr',
      ocrConfidence: { $lt: threshold }
    })
      .sort({ ocrConfidence: 1 })
      .limit(limit)
      .lean();

    return prompts;
  } catch (error) {
    console.error('Error getting low confidence OCR prompts:', error);
    return [];
  }
}

/**
 * Update a prompt (for corrections/improvements)
 */
export async function updatePrompt(
  promptId: string,
  updates: Partial<Prompt>
): Promise<{ success: boolean; error?: string }> {
  try {
    await connect();
    const promptObjectId = Types.ObjectId.createFromHexString(promptId);

    const result = await PromptModel.updateOne(
      { _id: promptObjectId },
      { $set: updates }
    );

    if (result.modifiedCount === 0) {
      return { success: false, error: 'Prompt not found or no changes made' };
    }

    return { success: true };
  } catch (error) {
    console.error('Error updating prompt:', error);
    return { success: false, error: 'Failed to update prompt' };
  }
}

/**
 * Get prompts by source (for PYQ tracking)
 */
export async function getPromptsBySource(source: string): Promise<Prompt[]> {
  try {
    await connect();
    const prompts = await PromptModel.find({ source }).lean();
    return prompts;
  } catch (error) {
    console.error('Error getting prompts by source:', error);
    return [];
  }
}

// ============================================================================
// NEW SCHEMA OPERATIONS - ExamQuestion (Exam-specific Question Instances)
// ============================================================================

/**
 * Create an exam question instance
 * Used by: Exam creation flow
 */
export async function createExamQuestion(examQuestionData: {
  promptId: string;
  options?: Array<{ text: string; isCorrect: boolean }>;
  marks: number;
  negativeMarks?: number;
  answerType: 'mcq' | 'multiple-select' | 'short' | 'long';
}): Promise<{ success: boolean; examQuestionId?: string; error?: string }> {
  try {
    // Validate input
    const validationResult = examQuestionZodSchema.safeParse({
      ...examQuestionData,
      _id: undefined,
      createdAt: new Date()
    });

    if (!validationResult.success) {
      return {
        success: false,
        error: `Validation failed: ${validationResult.error.message}`
      };
    }

    await connect();

    const examQuestion = new ExamQuestionModel(validationResult.data);
    const savedExamQuestion = await examQuestion.save();

    console.log('ExamQuestion created:', savedExamQuestion._id);
    return { success: true, examQuestionId: savedExamQuestion._id.toString() };
  } catch (error) {
    console.error('Error creating exam question:', error);
    return { success: false, error: 'Failed to create exam question' };
  }
}

/**
 * Bulk create exam questions
 * Used by: Exam creation with multiple questions
 */
export async function createExamQuestionsBulk(
  examQuestionsData: Array<{
    promptId: string;
    options?: Array<{ text: string; isCorrect: boolean }>;
    marks: number;
    negativeMarks?: number;
    answerType: 'mcq' | 'multiple-select' | 'short' | 'long';
  }>
): Promise<{ success: boolean; examQuestionIds?: string[]; error?: string }> {
  try {
    await connect();

    // Validate all exam questions
    const validatedExamQuestions = examQuestionsData.map(data => {
      const result = examQuestionZodSchema.safeParse({
        ...data,
        _id: undefined,
        createdAt: new Date()
      });
      if (!result.success) {
        throw new Error(`ExamQuestion validation failed: ${result.error.message}`);
      }
      return result.data;
    });

    const insertedExamQuestions = await ExamQuestionModel.insertMany(validatedExamQuestions);
    const examQuestionIds = insertedExamQuestions.map(eq => eq._id.toString());

    console.log(`Created ${examQuestionIds.length} exam questions in bulk`);
    return { success: true, examQuestionIds };
  } catch (error) {
    console.error('Error creating exam questions in bulk:', error);
    return { success: false, error: 'Failed to create exam questions in bulk' };
  }
}

/**
 * Get exam question with populated prompt details
 * Used by: Exam taking UI, exam preview
 */
export async function getExamQuestionWithPrompt(examQuestionId: string): Promise<any> {
  try {
    await connect();
    const examQuestionObjectId = Types.ObjectId.createFromHexString(examQuestionId);

    const result = await ExamQuestionModel.aggregate([
      { $match: { _id: examQuestionObjectId } },
      {
        $lookup: {
          from: 'prompts',
          let: { promptIdStr: { $toString: '$promptId' } },
          pipeline: [
            { $addFields: { idStr: { $toString: '$_id' } } },
            { $match: { $expr: { $eq: ['$idStr', '$$promptIdStr'] } } }
          ],
          as: 'promptDetails'
        }
      },
      { $unwind: '$promptDetails' }
    ]);

    return result.length > 0 ? result[0] : null;
  } catch (error) {
    console.error('Error getting exam question with prompt:', error);
    return null;
  }
}

/**
 * Get multiple exam questions with prompt details (for full exam)
 */
export async function getExamQuestionsWithPrompts(examQuestionIds: string[]): Promise<any[]> {
  try {
    await connect();
    const examQuestionObjectIds = examQuestionIds.map(id => Types.ObjectId.createFromHexString(id));

    const results = await ExamQuestionModel.aggregate([
      { $match: { _id: { $in: examQuestionObjectIds } } },
      {
        $lookup: {
          from: 'prompts',
          let: { promptIdStr: { $toString: '$promptId' } },
          pipeline: [
            { $addFields: { idStr: { $toString: '$_id' } } },
            { $match: { $expr: { $eq: ['$idStr', '$$promptIdStr'] } } }
          ],
          as: 'promptDetails'
        }
      },
      { $unwind: '$promptDetails' }
    ]);

    return results;
  } catch (error) {
    console.error('Error getting exam questions with prompts:', error);
    return [];
  }
}

/**
 * Find all exams using a specific prompt
 * Used by: Impact analysis when editing prompts
 */
export async function getExamsUsingPrompt(promptId: string): Promise<string[]> {
  try {
    await connect();
    
    // Find all ExamQuestions that reference this prompt
    const examQuestions = await ExamQuestionModel.find({ promptId }).select('_id').lean();
    const examQuestionIds = examQuestions.map(eq => eq._id.toString());

    if (examQuestionIds.length === 0) {
      return [];
    }

    // Find all Exams that reference these ExamQuestions
    const exams = await ExamModel.find({
      questions: { $in: examQuestionIds }
    }).select('_id examTitle').lean();

    return exams.map(e => e._id.toString());
  } catch (error) {
    console.error('Error finding exams using prompt:', error);
    return [];
  }
}

// ============================================================================
// UPDATED EXAM OPERATIONS (using new schema structure)
// ============================================================================

/**
 * Create exam with prompts (new schema)
 * This creates ExamQuestion instances and links them to an Exam
 */
export async function createExamWithPrompts(examData: {
  examTitle: string;
  examDescription: string;
  subject: string;
  examDegree: string;
  examType: string;
  passingPercentage: number;
  duration?: number;
  scheduledAt?: Date;
  createdBy: string;
  instructions?: string;
  negativeMarking?: boolean;
  negativeMarkingPercentage?: number;
  assignedUsers: string[]; // Array of user IDs
  questions: Array<{
    promptId: string;
    marks: number;
    negativeMarks?: number;
    answerType: 'mcq' | 'multiple-select' | 'short' | 'long';
    options?: Array<{ text: string; isCorrect: boolean }>;
  }>;
}): Promise<{ success: boolean; examId?: string; error?: string }> {
  try {
    await connect();

    // Step 1: Create ExamQuestion instances
    const examQuestionsData = examData.questions.map(q => ({
      promptId: q.promptId,
      options: q.options,
      marks: q.marks,
      negativeMarks: q.negativeMarks,
      answerType: q.answerType
    }));

    const examQuestionsResult = await createExamQuestionsBulk(examQuestionsData);
    if (!examQuestionsResult.success || !examQuestionsResult.examQuestionIds) {
      return { success: false, error: examQuestionsResult.error };
    }

    // Step 2: Calculate total marks
    const examMaxMarks = examData.questions.reduce((sum, q) => sum + q.marks, 0);

    // Step 3: Create Exam
    const exam = new ExamModel({
      examTitle: examData.examTitle,
      examDescription: examData.examDescription,
      subject: examData.subject,
      examDegree: examData.examDegree,
      examType: examData.examType,
      passingPercentage: examData.passingPercentage,
      examMaxMarks,
      duration: examData.duration,
      scheduledAt: examData.scheduledAt,
      createdBy: examData.createdBy,
      instructions: examData.instructions,
      negativeMarking: examData.negativeMarking || false,
      negativeMarkingPercentage: examData.negativeMarkingPercentage,
      questions: examQuestionsResult.examQuestionIds, // Array of ExamQuestion IDs
      assignedUsers: examData.assignedUsers,
      createdAt: new Date()
    });

    const savedExam = await exam.save();

    // Step 4: Update assigned users
    await UserModel.updateMany(
      { _id: { $in: examData.assignedUsers } },
      { $addToSet: { currentAllocatedExams: savedExam._id.toString() } }
    );

    console.log('Exam created with prompts:', savedExam._id);
    return { success: true, examId: savedExam._id.toString() };
  } catch (error) {
    console.error('Error creating exam with prompts:', error);
    return { success: false, error: 'Failed to create exam with prompts' };
  }
}

/**
 * Get exam with full question details (3-level join: Exam → ExamQuestion → Prompt)
 * Used by: Student exam page, teacher preview
 */
export async function getExamWithFullDetails(examId: string): Promise<any> {
  try {
    await connect();
    const examObjectId = Types.ObjectId.createFromHexString(examId);

    const result = await ExamModel.aggregate([
      { $match: { _id: examObjectId } },
      {
        $lookup: {
          from: 'examquestions',
          let: { questionIds: '$questions' },
          pipeline: [
            {
              $match: {
                $expr: {
                  $in: [{ $toString: '$_id' }, '$$questionIds']
                }
              }
            },
            {
              $lookup: {
                from: 'prompts',
                let: { promptIdStr: { $toString: '$promptId' } },
                pipeline: [
                  { $addFields: { idStr: { $toString: '$_id' } } },
                  { $match: { $expr: { $eq: ['$idStr', '$$promptIdStr'] } } }
                ],
                as: 'promptData'
              }
            },
            { $unwind: '$promptData' }
          ],
          as: 'questionDetails'
        }
      }
    ]);

    return result.length > 0 ? result[0] : null;
  } catch (error) {
    console.error('Error getting exam with full details:', error);
    return null;
  }
}

/**
 * Assign exam to additional users
 */
export async function assignExamToUsers(
  examId: string,
  userIds: string[]
): Promise<{ success: boolean; error?: string }> {
  try {
    await connect();

    // Update exam
    await ExamModel.updateOne(
      { _id: examId },
      { $addToSet: { assignedUsers: { $each: userIds } } }
    );

    // Update users
    await UserModel.updateMany(
      { _id: { $in: userIds } },
      { $addToSet: { currentAllocatedExams: examId } }
    );

    return { success: true };
  } catch (error) {
    console.error('Error assigning exam to users:', error);
    return { success: false, error: 'Failed to assign exam to users' };
  }
}

// ============================================================================
// UPDATED SUBMISSION OPERATIONS (using new schema with userId)
// ============================================================================

/**
 * Start exam submission (new schema with userId)
 */
export async function startExamSubmission(
  examId: string,
  userId: string
): Promise<{ success: boolean; submissionId?: string; error?: string }> {
  try {
    await connect();

    // Check if submission already exists
    const existingSubmission = await ExamSubmissionModel.findOne({
      examId,
      userId
    });

    if (existingSubmission) {
      return { 
        success: false, 
        error: 'Exam submission already exists',
        submissionId: existingSubmission._id.toString()
      };
    }

    // Create new submission
    const submission = new ExamSubmissionModel({
      examId,
      userId,
      status: 'IN_PROGRESS',
      responses: [],
      startedAt: new Date(),
      timeSpent: 0
    });

    const savedSubmission = await submission.save();
    console.log('Exam submission started:', savedSubmission._id);

    return { success: true, submissionId: savedSubmission._id.toString() };
  } catch (error) {
    console.error('Error starting exam submission:', error);
    return { success: false, error: 'Failed to start exam submission' };
  }
}

/**
 * Update exam submission (save progress)
 */
export async function updateExamSubmission(
  submissionId: string,
  updates: {
    responses?: Array<{
      examQuestionId: string;
      response: string | number[];
      isCorrect?: boolean;
    }>;
    timeSpent?: number;
  }
): Promise<{ success: boolean; error?: string }> {
  try {
    await connect();

    const result = await ExamSubmissionModel.updateOne(
      { _id: submissionId, status: 'IN_PROGRESS' },
      { $set: updates }
    );

    if (result.matchedCount === 0) {
      return { success: false, error: 'Submission not found or already submitted' };
    }

    return { success: true };
  } catch (error) {
    console.error('Error updating exam submission:', error);
    return { success: false, error: 'Failed to update exam submission' };
  }
}

/**
 * Submit exam (finalize submission)
 */
export async function finalizeExamSubmission(
  submissionId: string,
  autoSubmitted: boolean = false
): Promise<{ success: boolean; error?: string }> {
  try {
    await connect();

    const result = await ExamSubmissionModel.updateOne(
      { _id: submissionId },
      {
        $set: {
          status: 'SUBMITTED',
          submittedAt: new Date(),
          autoSubmitted
        }
      }
    );

    if (result.matchedCount === 0) {
      return { success: false, error: 'Submission not found' };
    }

    // Move exam from currentAllocatedExams to submissionHistory
    const submission = await ExamSubmissionModel.findById(submissionId).select('userId examId');
    if (submission) {
      await UserModel.updateOne(
        { _id: submission.userId },
        {
          $pull: { currentAllocatedExams: submission.examId },
          $addToSet: { submissionHistory: submissionId }
        }
      );
    }

    return { success: true };
  } catch (error) {
    console.error('Error finalizing exam submission:', error);
    return { success: false, error: 'Failed to finalize exam submission' };
  }
}

/**
 * Evaluate exam submission (grade and provide feedback)
 */
export async function evaluateExamSubmission(
  submissionId: string,
  evaluation: {
    totalScore: number;
    responses: Array<{
      examQuestionId: string;
      allottedMarks: number;
      feedback?: string;
    }>;
  }
): Promise<{ success: boolean; error?: string }> {
  try {
    await connect();

    const submission = await ExamSubmissionModel.findById(submissionId);
    if (!submission) {
      return { success: false, error: 'Submission not found' };
    }

    // Update responses with marks and feedback
    const updatedResponses = submission.responses.map(response => {
      const evalResponse = evaluation.responses.find(
        er => er.examQuestionId === response.examQuestionId
      );
      return {
        ...response,
        allottedMarks: evalResponse?.allottedMarks ?? 0,
        feedback: evalResponse?.feedback
      };
    });

    await ExamSubmissionModel.updateOne(
      { _id: submissionId },
      {
        $set: {
          status: 'EVALUATED',
          evaluatedAt: new Date(),
          totalScore: evaluation.totalScore,
          responses: updatedResponses
        }
      }
    );

    return { success: true };
  } catch (error) {
    console.error('Error evaluating exam submission:', error);
    return { success: false, error: 'Failed to evaluate exam submission' };
  }
}
