import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

    <html lang="en" className="min-h-[100vh] min-w-full">
      <body className="min-h-[100vh] l">
      <Header prompts={"profile"}/>
        {children}
      </body>
    </html>
    </ClerkProvider>
 
  );
}
