//to do : add error handling and logging, remove console logs in production , Make all the mongoose models global so that they are not created every time


//IMPORTANT!! NOTE:- when using this file, make sure to call connectToDb() first to ensure the database connection is established else it may throw an error in production
import { connect, disconnect } from "./connect.js";
import { getQuestionModel, getExamModel } from "./mongooseSchemas.js";
import type { Model } from "mongoose";
import type { Question, Exam } from "./schemas";   // <- generated by zod-to-mongoose

const QuestionModel: Model<Question> = getQuestionModel();
const ExamModel:     Model<Exam>     = getExamModel();

/**
 * Creates an exam together with its questions.
 * All parameters must already be validated by the caller.
 */
export async function createExam(
  examTitle: string,
  examDescription: string,
  examType: string,
  examMaxMarks: number,
  passingPercentage: number,
  examDegree: string,
  examUsers: string[],
  clientQuestions: {
    text: string;
    marks: number;
    type?: "mcq" | "theory";
    options?: string[];
    answer?: string;
  }[]
) {
  await connect();            // throws if connection fails

  /* --------------------- QUESTIONS ---------------------- */
  const questionDocs = clientQuestions.map(q => ({
    text:  q.text,                     // required
    type:  q.type    ?? "theory",              // required ⇒ default to "theory"
    options: q.options ?? [],                  // optional
    answer:  q.answer  ?? "NOT PRESENT"        // optional
  }));

  const inserted = await QuestionModel.insertMany(questionDocs);

  const questionsForExam = inserted.map((doc, i) => ({
    questionId: doc._id.toString(),
    marks:      clientQuestions[i].marks
  }));

  /* ----------------------- EXAM ------------------------- */
  const exam = new ExamModel({
    examTitle,
    examDescription,
    examType,
    examMaxMarks,
    passingPercentage,
    examDegree,
    examUsers,
    questions: questionsForExam          // <-- property name per examZodSchema
  });

  const savedExam = await exam.save();
  await disconnect();
  return savedExam;
}
export async function getExamSets(email) {
  try{

    await connect()
  }catch(err){
    console.log(err)
  }
  try{
    const examSets = await ExamModel.find({ examUsers: email },{__v:0});
    console.log(examSets);
    return JSON.parse(JSON.stringify(examSets));
  }catch(err){
    console.log(err)
  }
  
}
export async function getQuestions(userId,examId) {
  await connect();
  try {
    const results = await QuestionModel.find(
      { examUsers: email },
      {
        _id: 0,
        examquestions: 1,
        examName: 1,
        examDegree: 1,
        examFollowup: 1,
        examMaxMarks: 1,
      }
    );
    console.log(results);
    return JSON.parse(JSON.stringify(results));
  } catch (error) {
    console.error("Error fetching questions:", error);
    return [];
  }
}
// export async function updateResponses(id, response) {
//   const examSets = await QuestionModel();
//   examSets.updateOne({ _id: id }, { $push: { studentsResponse: response } });
//   questions
//     .save() // Saving the new user document to the database
//     .then((exams) => console.log("Responses were updated", exams))
//     .catch((error) => console.error(error)); // On error, log the error
// }

// export async function setUser(userEmail) {
//   await connect();
//   try {
//     const users = await getuserModel();
//     console.log(users);
//     console.log(await users.find({ userEmail: userEmail }));
//     if ((await users.find({ useremail: userEmail })).length == 0) {
//       const user = new users({
//         useremail: userEmail,
//       });
//       user.save().then(() => {
//         console.log("new user created" + user);
//       });
//     } else {
//       console.log(
//         "if statemment failed dude to " +
//           (await users.find({ userEmail: userEmail }).length),
//         users.find({ userEmail: userEmail }).length == 0
//       );
//     }
//   } catch (error) {
//     console.log(
//       "error occured when creating data of user in the database" + error
//     );
//   }
// }

// export async function getUserRole(email) {
//   await connect();
//   try {
//     const userModel = await getuserModel();
//     const results = await userModel.find({ useremail: email });
//     console.log(
//       "Data fetched from the database and the user is " + results[0].userRole
//     );
//     return results[0].userRole;
//   } catch (error) {
//     console.log(error);
//   }
// }

// export async function getUsers() {
//   try {
//     const userModel = await getuserModel();
//     const result = await userModel.find({}, { _id: 0, __v: 0 }).lean();
//     console.log(result);
//     return result;
//   } catch (error) {
//     console.log("an error occured when fetching the users data", error);
//   }
// }

// export async function changeRoles(email, role) {
//   try {
//     const userModel = await getuserModel();
//     userModel
//       .updateOne({ useremail: email }, { userRole: role })
//       .then((results) => {
//         console.log(results);
//       });
//   } catch (error) {
//     console.log("error while making user " + role + " error= " + error);
//   }
// }

// export async function createSubject(
//   subjectName,
//   subjectDescription,
//   subjectDegree,
//   subjectMarks,
//   subjectUsers,
//   subjectPyq,
//   subjectSyllabus
//   // subjectImage
// ) {
//   try {
//     await connect();
//     const subjectModel = await getsubjectModel();
//     const name = await subjectModel.find({ subjectName: subjectName });
//     if (!_.isEmpty(name)) {
//       throw new Error("Subject Name already taken");
//     }
//     const newSubject = new subjectModel({
//       subjectName: subjectName,
//       subjectDescription: subjectDescription,
//       subjectDegree: subjectDegree,
//       subjectMarks: subjectMarks,
//       subjectUsers: subjectUsers,
//       subjectPyq: subjectPyq,
//       subjectSyllabus: subjectSyllabus,
//       // subjectImage: subjectImage,
//     });
//     newSubject.save();
//     console.log("yay");
//     return { success: true };
//   } catch (error) {
//     console.log(error);
//     return { success: false, message: error };
//   }
// }

// export async function updateSubjectRatings(subjectName, rating, feedback) {
//   try {
//     await connect();
//     const subjectModel = await getsubjectModel();
//     const subject = await subjectModel.findOne({ subjectName: subjectName });
//     const totalRatings = subject.totalRating;
//     const numberOfReviews = subject.numberOfReviews;
//     subjectModel
//       .findOneAndUpdate(
//         { subjectName: subjectName },
//         {
//           $push: {
//             subjectReview: {
//               studentRating: rating,
//               studentFeedback: feedback,
//             },
//           },
//           totalRating: totalRatings + rating,
//           numberOfReviews: numberOfReviews + 1,
//         },
//         { new: true, returnOriginal: false }
//       )
//       .then((result) => {
//         console.log(result);
//       })
//       .then((error) => {
//         if (error) {
//           console.log(error);
//         }
//       });

//     console.log("yay");
//     return "Rating updated sucessfully";
//   } catch (error) {
//     console.log(error);
//     return error;
//   }
// }

// export async function getSubjects(userEmail) {
//   try {
//     await connect();
//     console.log("get sub working email");
//     console.log(userEmail);
//     const subjectModel = await getsubjectModel();
//     const userSubjects = await subjectModel
//       .find({ subjectUsers: userEmail })
//       .select({
//         subjectName: 1,
//         subjectDescription: 1,
//         subjectDegree: 1,
//         _id: 0,
//       });
//     console.log(userSubjects);
//     return JSON.parse(JSON.stringify(userSubjects));
//   } catch (error) {
//     return error;
//   }
// }

// // createSubject(
// //   "oose",
// //   "hehehe",
// //   "btech",
// //   90,
// //   "bobby.k@somaiya.edu",
// //   "eesa"
// // ).then((result) => {
// //   console.log(result);
// // });
// // updateSubjectRatings("oose", 10, "nah");
