import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";

import {
  MANAGED_COLLECTION_NAMES,
  isManagedCollectionName,
  listCollectionsWithLeftovers,
  summarizeTruncation,
} from "../../packages/backend/src/database/managedCollections.ts";

import {
  BACKUP_ID_PATTERN,
  chunkDocuments,
  formatBackupErrors,
  isValidBackupId,
  planRestore,
  RESTORE_BATCH_SIZE,
  summarizeBackupReads,
} from "../../packages/backend/src/services/backupPlan.ts";

import {
  buildJobStatusPayload,
  isTerminalJobStatus,
  JOB_STATUS_SOURCE,
  shouldPollJobStatus,
} from "../../packages/frontend/lib/jobStatus.ts";

import {
  DEFAULT_RETENTION_DAYS,
  MAX_RETENTION_DAYS,
  parseRetentionDays,
} from "../../packages/frontend/lib/jobCleanup.ts";

import {
  buildAiPipelineUrl,
  DEFAULT_AI_PIPELINE_URL,
  getAiPipelineBaseUrl,
} from "../../packages/frontend/lib/aiPipeline.ts";

describe("managed collection registry", () => {
  it("covers every collection the admin dashboard reports", () => {
    for (const name of [
      "questions",
      "examSets",
      "user",
      "ExamSubmission",
      "Prompt",
      "ExamQuestion",
      "subjects",
      "JobMetadata",
      "UploadSession",
      "AnalysisReport",
      "ExamAnalysis",
      "PastPaper",
      "Syllabus",
      "UniqueQuestion",
    ]) {
      assert.ok(isManagedCollectionName(name), `${name} must be managed`);
    }
  });

  it("manages the new feature Subject collection (truncate used to skip it)", () => {
    assert.ok(
      isManagedCollectionName("Subject"),
      "Subject must be truncated/backed up, not just counted"
    );
    assert.notEqual(
      MANAGED_COLLECTION_NAMES.filter((name) => name === "Subject").length > 0,
      false
    );
  });

  it("keeps the legacy and new subject collections distinct and has no duplicates", () => {
    assert.equal(new Set(MANAGED_COLLECTION_NAMES).size, MANAGED_COLLECTION_NAMES.length);
    assert.ok(isManagedCollectionName("subjects"));
    assert.ok(isManagedCollectionName("Subject"));
    assert.equal(MANAGED_COLLECTION_NAMES.length, 15);
  });

  it("rejects unknown collection names", () => {
    assert.equal(isManagedCollectionName("secrets"), false);
    assert.equal(isManagedCollectionName(undefined), false);
  });
});

describe("summarizeTruncation", () => {
  it("totals deleted documents and reports no errors", () => {
    const summary = summarizeTruncation({
      questions: { before: 10, deleted: 10 },
      Subject: { before: 4, deleted: 4 },
    });
    assert.deepEqual(summary, { totalDeleted: 14, totalBefore: 14, hasErrors: false });
  });

  it("flags a run that hit an error in any collection", () => {
    const summary = summarizeTruncation({
      questions: { before: 10, deleted: 10 },
      ExamAnalysis: { before: 0, deleted: 0, error: "not authorized on collection" },
    });
    assert.equal(summary.hasErrors, true);
    assert.equal(summary.totalDeleted, 10);
  });

  it("reports collections that still hold documents", () => {
    const leftovers = listCollectionsWithLeftovers({
      questions: { before: 10, deleted: 10 },
      Syllabus: { before: 5, deleted: 0 },
      PastPaper: { before: 2, deleted: 0, error: "boom" },
    });
    assert.deepEqual(leftovers, ["Syllabus", "PastPaper"]);
  });
});

describe("isValidBackupId", () => {
  it("accepts ids generated by createBackup", () => {
    const id = `backup_${new Date().toISOString().replace(/[:.]/g, "-")}`;
    assert.match(id, BACKUP_ID_PATTERN);
    assert.equal(isValidBackupId(id), true);
  });

  it("rejects ids that are not backup ids", () => {
    for (const id of ["", "..", "../other-prefix", "backup_../../etc/passwd", "latest", null, 42]) {
      assert.equal(isValidBackupId(id), false, `${String(id)} must be rejected`);
    }
  });
});

describe("planRestore", () => {
  it("includes every managed collection even when the backup predates it", () => {
    const plan = planRestore({ questions: [{ _id: 1 }] }, MANAGED_COLLECTION_NAMES);
    assert.equal(plan.length, MANAGED_COLLECTION_NAMES.length);
    assert.deepEqual(
      plan.map((entry) => entry.name),
      [...MANAGED_COLLECTION_NAMES]
    );
  });

  it("marks collections missing from the payload so they are still cleared", () => {
    const plan = planRestore({ questions: [{ _id: 1 }] }, MANAGED_COLLECTION_NAMES);
    const subject = plan.find((entry) => entry.name === "Subject");
    assert.ok(subject);
    assert.equal(subject!.presentInBackup, false);
    assert.deepEqual(subject!.docs, []);
  });

  it("keeps documents for collections that are present", () => {
    const plan = planRestore({ Subject: [{ name: "Maths" }] }, MANAGED_COLLECTION_NAMES);
    const subject = plan.find((entry) => entry.name === "Subject")!;
    assert.equal(subject.presentInBackup, true);
    assert.equal(subject.docs.length, 1);
  });

  it("treats a corrupt payload as empty instead of throwing", () => {
    for (const payload of [null, undefined, "not-an-object", 42, [1, 2, 3]]) {
      const plan = planRestore(payload, MANAGED_COLLECTION_NAMES);
      assert.equal(plan.length, MANAGED_COLLECTION_NAMES.length);
      assert.ok(plan.every((entry) => entry.docs.length === 0));
      assert.ok(plan.every((entry) => entry.presentInBackup === false));
    }
  });

  it("ignores collections that are not managed", () => {
    const plan = planRestore({ auditLog: [{ _id: 1 }] }, MANAGED_COLLECTION_NAMES);
    assert.ok(!plan.some((entry) => entry.name === "auditLog"));
  });
});

describe("chunkDocuments", () => {
  it("splits documents into batches without losing or duplicating any", () => {
    const docs = Array.from({ length: 250 }, (_, index) => ({ index }));
    const batches = chunkDocuments(docs, 100);
    assert.deepEqual(
      batches.map((batch) => batch.length),
      [100, 100, 50]
    );
    assert.deepEqual(batches.flat(), docs);
  });

  it("returns no batches for empty input", () => {
    assert.deepEqual(chunkDocuments([], 100), []);
    assert.deepEqual(chunkDocuments(undefined as any, 100), []);
  });

  it("falls back to the default batch size for invalid values", () => {
    const docs = Array.from({ length: RESTORE_BATCH_SIZE + 5 }, (_, index) => index);
    for (const size of [0, -10, Number.NaN, Number.POSITIVE_INFINITY]) {
      const batches = chunkDocuments(docs, size);
      assert.deepEqual(
        batches.map((batch) => batch.length),
        [RESTORE_BATCH_SIZE, 5]
      );
    }
  });
});

describe("summarizeBackupReads", () => {
  it("marks a backup as failed when a collection could not be read", () => {
    const result = summarizeBackupReads(
      { questions: 3, Subject: 0 },
      { questions: [{ _id: 1 }], Subject: [] },
      { Subject: "not authorized on Subject" }
    );
    assert.equal(result.status, "failed");
    assert.match(formatBackupErrors(result.errors), /Subject: not authorized on Subject/);
  });

  it("marks a backup as completed when every collection was read", () => {
    const result = summarizeBackupReads({ questions: 3 }, { questions: [] }, {});
    assert.equal(result.status, "completed");
    assert.equal(result.errors && Object.keys(result.errors).length, 0);
  });
});

describe("job status helpers", () => {
  it("treats success, failed and partial_success as terminal", () => {
    for (const status of ["success", "failed", "partial_success"]) {
      assert.equal(isTerminalJobStatus(status), true, status);
      assert.equal(shouldPollJobStatus(status), false, status);
    }
  });

  it("keeps polling unfinished and unknown statuses", () => {
    for (const status of ["in_progress", "pending", "queued", "", undefined]) {
      assert.equal(shouldPollJobStatus(status), true, String(status));
    }
  });

  it("builds a payload without leaking mongo internals", () => {
    const payload = buildJobStatusPayload(
      {
        _id: "68b0",
        __v: 3,
        job_id: "job-1",
        filename: "paper.pdf",
        status: "success",
        stages: { ocr: "done" },
        s3_pdf_key: "uploads/paper.pdf",
      },
      JOB_STATUS_SOURCE.mongodb
    );

    assert.ok(payload);
    assert.equal(payload!.job_id, "job-1");
    assert.equal(payload!.source, "mongodb");
    assert.equal("_id" in payload!, false);
    assert.equal("__v" in payload!, false);
  });

  it("returns null when there is no cached job", () => {
    assert.equal(buildJobStatusPayload(null, JOB_STATUS_SOURCE.mongodb), null);
    assert.equal(buildJobStatusPayload(undefined, JOB_STATUS_SOURCE.mongodb), null);
  });

  it("can attach a staleness warning to the cached payload", () => {
    const payload = buildJobStatusPayload({ job_id: "job-2", status: "in_progress" }, JOB_STATUS_SOURCE.mongodbStale, {
      warning: "AI pipeline unavailable, showing cached data",
    });
    assert.equal(payload!.source, "mongodb-stale");
    assert.match(String(payload!.warning), /pipeline unavailable/);
  });
});

describe("parseRetentionDays", () => {
  it("defaults to 90 days when nothing is provided", () => {
    for (const value of [undefined, null, ""]) {
      const result = parseRetentionDays(value);
      assert.equal(result.ok, true);
      assert.equal(result.days, DEFAULT_RETENTION_DAYS);
    }
  });

  it("keeps an explicit value of 1 instead of falling back to the default", () => {
    const result = parseRetentionDays(1);
    assert.equal(result.ok, true);
    assert.equal(result.days, 1);
  });

  it("accepts numeric strings from the query string", () => {
    const result = parseRetentionDays("45");
    assert.equal(result.ok, true);
    assert.equal(result.days, 45);
  });

  it("rejects a zero or negative retention window (would expire every job)", () => {
    for (const value of [0, -1, -90]) {
      const result = parseRetentionDays(value);
      assert.equal(result.ok, false, String(value));
      assert.match(String(result.error), /between 1 and 3650/);
      assert.equal(result.days, DEFAULT_RETENTION_DAYS);
    }
  });

  it("rejects non-integer, non-numeric and absurdly large values", () => {
    for (const value of ["abc", "12abc", 1.5, Number.NaN, Number.POSITIVE_INFINITY, true, {}, MAX_RETENTION_DAYS + 1]) {
      const result = parseRetentionDays(value);
      assert.equal(result.ok, false, JSON.stringify(value));
    }
  });

  it("accepts the maximum retention window", () => {
    const result = parseRetentionDays(MAX_RETENTION_DAYS);
    assert.equal(result.ok, true);
    assert.equal(result.days, MAX_RETENTION_DAYS);
  });
});

describe("ai pipeline url helpers", () => {
  it("defaults to the documented loopback address, not a LAN ip", () => {
    const previous = process.env.AI_PIPELINE_URL;
    delete process.env.AI_PIPELINE_URL;
    try {
      assert.equal(getAiPipelineBaseUrl(), DEFAULT_AI_PIPELINE_URL);
      assert.match(getAiPipelineBaseUrl(), /^http:\/\/127\.0\.0\.1:5000$/);
    } finally {
      if (previous === undefined) delete process.env.AI_PIPELINE_URL;
      else process.env.AI_PIPELINE_URL = previous;
    }
  });

  it("ignores blank configuration and strips trailing slashes", () => {
    const previous = process.env.AI_PIPELINE_URL;
    try {
      process.env.AI_PIPELINE_URL = "   ";
      assert.equal(getAiPipelineBaseUrl(), DEFAULT_AI_PIPELINE_URL);
      process.env.AI_PIPELINE_URL = "https://pipeline.example.com/";
      assert.equal(getAiPipelineBaseUrl(), "https://pipeline.example.com");
    } finally {
      if (previous === undefined) delete process.env.AI_PIPELINE_URL;
      else process.env.AI_PIPELINE_URL = previous;
    }
  });

  it("joins base url and path exactly once", () => {
    assert.equal(
      buildAiPipelineUrl("/job/abc/status", "http://127.0.0.1:5000"),
      "http://127.0.0.1:5000/job/abc/status"
    );
    assert.equal(
      buildAiPipelineUrl("job/abc/questions", "http://127.0.0.1:5000/"),
      "http://127.0.0.1:5000/job/abc/questions"
    );
  });
});

/**
 * Structural guards.
 *
 * The route handlers and the admin page cannot be imported here (they pull in
 * next/server, mongoose and React), so we assert on their source instead. Each
 * guard corresponds to a bug that shipped to main.
 */
function readRepoFile(relativePath: string): string {
  return readFileSync(new URL(`../../${relativePath}`, import.meta.url), "utf8");
}

function stripComments(source: string): string {
  return source.replace(/\/\*[\s\S]*?\*\//g, "").replace(/(^|[^:])\/\/.*$/gm, "$1");
}

describe("admin database + jobs surfaces", () => {
  it("stats, truncate and backup all resolve collections through the registry", () => {
    const surfaces = [
      "packages/frontend/app/api/admin/database/route.ts",
      "packages/frontend/app/api/admin/database/truncate/route.ts",
      "packages/backend/src/services/databaseBackupService.ts",
    ];

    for (const surface of surfaces) {
      const source = readRepoFile(surface);
      assert.match(
        source,
        /getManagedCollections|getAllCollections/,
        `${surface} must use the managed collection registry`
      );
      assert.doesNotMatch(
        source,
        /getUniqueQuestionModel\(\)/,
        `${surface} must not re-declare its own collection list`
      );
    }
  });

  it("truncate clears every managed collection", () => {
    const source = readRepoFile("packages/frontend/app/api/admin/database/truncate/route.ts");
    assert.match(source, /for \(const \{ name, model \} of collections\)/);
    assert.match(source, /deleteMany\(\{\}\)/);
  });

  it("admin database page never references the undefined setIsTruncating", () => {
    const source = stripComments(readRepoFile("packages/frontend/app/admin/database/page.tsx"));
    assert.doesNotMatch(
      source,
      /setIsTruncating/,
      "the hook owns isTruncating; calling setIsTruncating threw a ReferenceError"
    );
  });

  it("job UIs go through the /api proxies instead of the pipeline host", () => {
    for (const surface of [
      "packages/frontend/app/admin/upload/question-papers/page.tsx",
      "packages/frontend/app/upload-status/[sessionId]/page.tsx",
    ]) {
      const source = stripComments(readRepoFile(surface));
      assert.doesNotMatch(source, /localhost:5000|192\.168\./, `${surface} must not hardcode the pipeline URL`);
    }
  });
});
