import smtplib
import os
from email.message import EmailMessage
import constants
from codes import mailCode as code
from dotenv import load_dotenv

load_dotenv()

class mailer:
    def __init__(self):
        try:
            self.s=smtplib.SMTP('smtp.gmail.com', 587)
            self.s.starttls()
            self.admins=os.environ.get("APPLICATION_ADMIN").split(",")
            print(self.admins)
            self.s.login(os.environ.get("APPLICATION_EMAIL"), os.environ.get("APPLICATION_EMAIL_PASSWORD"))
            print("Login Successful")
            self.status={"code":code.SUCCESS,"message":"Login Successful"}
        
        except smtplib.SMTPAuthenticationError as e:
            print("Authentication Error:", e)
            self.status={"code":code.MAIL_AUTHENTICATION_ERROR,"message":str(e)}

        except smtplib.SMTPConnectError as e:
            print("Connection Error:", e)
            self.status={"code":code.MAIL_CONNECTION_ERROR,"message":str(e)}

        except smtplib.SMTPException as e:
            print("Error:", e)
            self.status={"code":code.UNKNOWN_ERROR,"message":str(e)}

        except Exception as e:
            print("Error:", e)
            self.status={"code":code.UNKNOWN_ERROR,"message":str(e)}


    def sendAlert(self,message:str,subject:str):
        try:
            s=self.s
            for mail in self.admins:
                msg = EmailMessage()
                msg['Subject'] = subject
                msg['From'] = os.environ.get("APPLICATION_EMAIL")
                msg['To'] = mail
                body = (
                f"Dear Admin,\n\n"
                f"This is an email regarding your application EESA.\n"
                f"There is an automated alert generated by the application.\n\n"
                f"{message}\n\n"
                f"Note: Do not reply to this email. Contact support if needed.\n\n"
                f"Thank you."
            )
            msg.set_content(body)
            s.send_message(msg)
            print("Mail Sent")
            return {"code":code.SUCCESS,"message":"Mail Sent"}

        except smtplib.SMTPAuthenticationError as e:
            print("Authentication Error:", e)
            self.status={"code":code.MAIL_AUTHENTICATION_ERROR,"message":str(e)}

        except smtplib.SMTPConnectError as e:
            print("Connection Error:", e)
            self.status={"code":code.MAIL_CONNECTION_ERROR,"message":str(e)}

        except smtplib.SMTPException as e:
            print("Erwwwror:", e)
            self.status={"code":code.UNKNOWN_MAIL_ERROR,"message":str(e)}

        except Exception as e:
            print("Erwwror:", e)
            return{"code":code.UNKNOWN_ERROR,"message":str(e)}